services:
  drone-srcb:
    build: .
    environment:
      API_ID: $API_ID  
      API_HASH: $API_HASH  
      BOT_TOKEN: $BOT_TOKEN 
      SESSION: $SESSION
      AUTH: $AUTH
      FORCESUB: $FORCESUB
      MONGO_URL: $MONGO_URL
    ports:
      - 8080
    resources:
      cpu: 1000m
      memory: 3Gi
